import Curve from '@/components/Layout/Curve'
import Head from 'next/head'

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve backgroundColor={"#000"}>
        <div className='w-layout-blockcontainer container-4 w-container'>
          <div className='sectionbg'>
  
                <img src="/about.png" alt="me" className='max-w-1/2 max-w-[600px]' /> 

          </div>
          <h1 class="heading-4">About </h1>
        
              <p class="techdesc wide">
                  Hi! I'm Zsolt, currently Budapest based software engineer.<br/><br/>Throughout my
                  professional career I've been always chasing the limits what the web platform is capable of, let it be
                  performance, UX, frameworks, accessibility, testing, monitoring and so on. <br/><br/>What drives me most
                  in my career is to be able to solve impactful, challenging customer problems by leveraging state of the
                  art technology, UI and innovation. <br/><br/>As a web developer my goal is to always present the user a
                  pleasing browsing experience via a well-designed, fast and performant interface. I'm a form believer of
                  the importance of first impression, and that's true for the any web application as well. I am
                  continually inspired by the ever-evolving web ecosystem, always seeking to explore and experiment with
                  new tools, technologies, and methodologies. I have a particular passion for WebGL visualizations and
                  their potential to create immersive, interactive web experiences. 


                  hroughout my career I've been lucky enough to work as a web dev for one of the few Hungarian unicorns
                  called LogMeIn: both in Budapest and in Boston, MA. After that I've joined Truemtion where I've switched
                  to become a team lead and engineering manager, still heavily involved in the technical side of things.
                  <br/><br/>When I'm not tinkering with bits and bytes I'm an extremely passionate
                  cyclist (road, xc, gravel you name it) and snowboarder. I'm also a certified woodworker, mostly working
                  on creative, fun projects for my family and friends.
                </p>
        </div>
      </Curve>
    </>
  )
}
