import Curve from '@/components/Layout/Curve'
import Head from 'next/head'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve backgroundColor="#000">
        <div className='w-layout-blockcontainer container-4 w-container'>
          <div className='sectionbg'>
          <img src="/techbg.png" alt="techbg" />
          </div>
          <h1 className='text-center text-primary mt-50'>Tech</h1>
          <p class="techdesc">Walkthrough of my professional journey alongside passion-driven pet projects.</p>
        </div>
        <div class="w-layout-blockcontainer workhistorywrapper w-container">
          <h2 class="heading-5">Work History</h2>
          <div class="historywrapper"><div class="date"><h3>CMT</h3><div class="workdate">'21 Oct - '24 Jun</div></div><div class="historydivider"></div><p class="historydetails">Have been leading and managing a full stack engineering team as we executed a complete rewrite of a Django web application to React and Tornado. As manager I’ve been responsible for product collaboration and timelines, engineering strategy and processes , personal career growth for team members and culture.</p></div>
          <div class="historywrapper"><div class="date"><h3>Truemotion</h3><div class="workdate">'18 Jan - '21 Oct</div></div><div class="historydivider"></div><p class="historydetails">Joined and opened an engineering office in Budapest to extend early stage, Boston based mobile telemetry startup called Truemotion. Have been leading efforts to introduce dev processes, agile, product planning and more as the office quickly grow to ~50. My main focus have been to build a complex web application from scratch, displaying the enormous amount of diverse driver behavioral data and trip data which has been collected by the Truemotion app. This resulted in an aesthetic visual representation of dashboards, graphs, maps, timelines. The company got later <a href="https://www.cmtelematics.com/news/cambridge-mobile-telematics-acquires-truemotion/" class="link-6">acquired</a> by it1s biggest rival, Cambridge Mobile Telematics.</p></div>
          <div class="historywrapper"><div class="date"><h3>Xively</h3><div class="workdate">'15 Feb - '17 Feb</div></div><div class="historydivider"></div><p class="historydetails">Moved out to Boston to join a newly acquired IoT startup named Xively. In the growing process I had been able to take part in designing the platform architecture, hiring and building up two teams (~5-6 people each), leading the developing efforts for the web dashboard for connected products, and implementing and maintaining the platform's microservices. The company got later <a href="https://techcrunch.com/2018/02/15/google-to-acquire-xively-iot-platform-from-logmein/" class="link-6">acquired</a> by Google.</p></div>
          <div class="historywrapper"><div class="date"><h3>LogMeIn</h3><div class="workdate">'10 Jan - '15 Feb</div></div><div class="historydivider"></div><p class="historydetails">Building <a href="https://www.logmein.com/hu/central" class="link-4">LogMeIn Central</a>, a web based administration platform to oversee and manage your fleet of remotely controlled computers. Also have been part of building the before-it-was-Zoom online collaboration tool called <a href="https://join.me/" class="link-5">join.me</a>.</p></div>
        </div>

        <div class="w-layout-blockcontainer workhistorywrapper w-container">
          <h2 class="heading-5">Personal Projects</h2>
          <div class="historywrapper"><div class="date"><h3>Zendorphin</h3><div class="workdate">'17 Sep</div></div><div class="historydivider"></div><p class="historydetails">Cycling group ride organizer platform. Imagine Facebook Events X Strava. I would've loved if a tool like this would have been around, where you can create ad-hoc rides, select route, invite friends, collect analytics and media on the same platform.This idea has been forever on my mind and once I've been between jobs I did give it a try. With a designer joining the project, we laid down the product and also creted a prototype, but a sudden job opportunity did cut the project from evolving further. Landing page: <a href="https://zendorphin.webflow.io/" class="link">https://zendorphin.webflow.io/</a></p></div>
          <div class="historywrapper"><div class="date"><h3>Curatist</h3><div class="workdate">'17 Jan</div></div><div class="historydivider"></div><p class="historydetails">A new-tab Chrome extension to collect inspiration and news materials for architects and designers alike. <a href="https://chromewebstore.google.com/detail/the-curatist/fohopadbjklifpfnnnfkkjpmjpjpjchk" class="link-2">https://chromewebstore.google.com/detail/the-curatist/fohopadbjklifpfnnnfkkjpmjpjpjchk</a></p></div>
          <div class="historywrapper"><div class="date"><h3>Velopedia</h3><div class="workdate">'14 Dec</div></div><div class="historydivider"></div><p class="historydetails">Also a new-tab chrome extension to have all the cycling world's updates in one place. It uses the <a href="http://scripting.com/2014/06/02/whatIsARiverOfNewsAggregator.html" class="link-3">river5</a> new aggregator under the hood for scraping and reading RSS. the API and middleware has been written in NodeJS.</p></div>
        </div>
      </Curve>
    </>
  )
}
